---
  header_logo_url: https://sfg.taxonworks.org/s/ya0sxk
  header_logo_text: Grylloblattodea Species File
  header_links:
    - label: Home
      link: /

    - label: Search DwC
      link: /resources/tw/filter/dwc_otus

    - label: About
      link: /about
