---
  header_logo_url:http://Grylloblattodea.archive.speciesfile.org/HomePage/Grylloblattodea/img_Logo/SiteLogo.jpg
  header_logo_text: Grylloblattodea Species File
  header_links:
    - label: Home
      link: /

    - label: About
      link: /about
