news_module:
  announcements:
    - message: Grylloblattodea Species File will be undergoing changes to accommodate its unification with several small Polyneoptera orders and several fossil orders of insects, as well as the addition of Archaeognatha and Zygentoma.
      url: ''
