---
  project_name: "Grylloblattodea Species File"
  project_citation: "Heidi Hopkins & Michael D. Maehr. Grylloblattodea Species File. Version 5.0/5.0. [retrieval date]. <http://Grylloblattodea.SpeciesFile.org>"
  project_authors: "Hopkins, H. and Maehr, M.D."
  project_url: "https://grylloblattodea.speciesfile.org."
  project_old_url: "http://grylloblattodea.archive.speciesfile.org." 
  focal_taxon: "grylloblattodea"
  focal_taxon_common_name: "ice crawlers"
  contact_email: "cockroachdoc@gmail.com"
